services:
  apigateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - employee-service
      - inventory-service
      - product-service
    networks:
      - lookstock-nt

  employee-service:
    build:
      context: ./employee-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./employee-service/.env
    networks:
      - lookstock-nt

  inventory-service:
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    env_file:
      - ./inventory-service/.env
    networks:
      - lookstock-nt

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    env_file:
      - ./product-service/.env
    networks:
      - lookstock-nt
networks:
  lookstock-nt:
    driver: bridge
