services:
  employee-service:
    build: ./employee-service
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=sqlserver://<usuario>:<contraseña>@<servidor>.database.windows.net:1433;database=<nombre_db>;encrypt=true
    networks:
      - microservices-network
    depends_on:
      - db


  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    networks:
      - microservices-network
    depends_on:
      - employee-service

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver_db
    environment:
      SA_PASSWORD: "TuPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
